# pandas : 데이터 처리 라이브러리
- 행*열의 2차원 데이터를 효율적으로 가공
- [pandas 공식 홈페이지](https://pandas.pydata.org/)

In [ ]:
# 설치
! pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (2.0.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.10/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas) (2023.4)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.10/dist-packages (from pandas) (2024.1)
Requirement already satisfied: numpy>=1.21.0 in /usr/local/lib/python3.10/dist-packages (from pandas) (1.25.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)

In [ ]:
# 사용
import pandas as pd

# Kaggle, Titanic 데이터 설명
- **Kaggle** : 데이터 분석 경진대회를 주최하는 플랫폼
- **Titanic** : 캐글의 대표적인 데이터 분석 입문용 데이터셋
  - [Titanic 데이터 다운로드](https://www.kaggle.com/c/titanic)

# pandas 데이터 형식
- **Series** : 1차원 배열
  - index와 value가 일대일 대응
- **DataFrame** : 행*열의 2차원 배열
  - DataFrame의 열은 각각의 Series 객체

### Series

In [ ]:
# 딕셔너리로 Series 생성
dict_data = {'a':1, 'b':2, "c":3}
series_data = pd.Series(dict_data)

In [ ]:
# 데이터 타입, 내용 확인
print(series_data)
print(type(series_data))

a    1
b    2
c    3
dtype: int64
<class 'pandas.core.series.Series'>

In [ ]:
# 리스트로 Series 생성
# 인덱스를 별도로 지정하지 않으면, 디폴트로 정수형 위치 인덱스가 지정됨
list_data = ['2024-07-18', 3.14, 'ABC', 100, True]
series_data = pd.Series(list_data)

In [ ]:
# 데이터 타입, 내용 확인
print(series_data)
print(type(series_data))

0    2024-07-18
1          3.14
2           ABC
3           100
4          True
dtype: object
<class 'pandas.core.series.Series'>

### DataFrame

In [ ]:
# 딕셔너리로 DataFrame 생성
dict_data = {'c0':[1,2,3],
             'c1':[4,5,6],
             'c2':[7,8,9],
             'c3':[10,11,12],
             'c4':[13,14,15]}
df = pd.DataFrame(dict_data)

In [ ]:
# 데이터 타입, 내용 확인
# 1열이 1시리즈이므로, 키값이 열 이름이 됨
print(df)
print(type(df))

   c0  c1  c2  c3  c4
0   1   4   7  10  13
1   2   5   8  11  14
2   3   6   9  12  15
<class 'pandas.core.frame.DataFrame'>

# 파일 불러오기
- **read_csv** & **to_csv**
- **read_excel** & **to_excel**
- **read_json** & **to_json**
- **read_sql** & **to_sql**
- **read_html** & **to_html**

In [ ]:
# csv 파일 업로드
titanic = pd.read_csv('/content/train.csv')

# 데이터 내용 확인
- **.columns** : 컬럼명 확인
- **.head()** : 상단 5행 출력
- **.tail()** : 하단 5행 출력
- **.shape** : (행, 열) 크기 확인
- **.info()** : 전반적인 정보
  - 행, 열 크기
  - 컬럼명
  - 컬럼 별 결측치
  - 컬럼 별 데이터 타입
- **type()** : 데이터타입 확인

In [ ]:
# .columns : 컬럼명 확인
print(titanic.columns)

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [ ]:
# .head() : 상단 5행 확인
titanic.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [ ]:
# 하단 3행 확인
titanic.tail(3)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q

In [ ]:
# .shape : (행,열) 크기 확인
titanic.shape

(891, 12)

In [ ]:
# .info() : 전반적인 정보
titanic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [ ]:
# type() : 데이터 타입 확인
type(titanic)

pandas.core.frame.DataFrame

# 특정 열 선택
- 열 1개 선택
  - ["열이름"]
  - .열이름
- 열 n개 선택
  - [["열이름"]]
- 열 1개를 데이터프레임 객체로 추출 : 이중대괄호[[  ]]

In [ ]:
# 열 1개 선택
# ["열이름"]
names = titanic['Name']
names.head()

0                              Braund, Mr. Owen Harris
1    Cumings, Mrs. John Bradley (Florence Briggs Th...
2                               Heikkinen, Miss. Laina
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                             Allen, Mr. William Henry
Name: Name, dtype: object

In [ ]:
# 열 1개 선택
# .열이름
names = titanic.Name
names.head()

0                              Braund, Mr. Owen Harris
1    Cumings, Mrs. John Bradley (Florence Briggs Th...
2                               Heikkinen, Miss. Laina
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                             Allen, Mr. William Henry
Name: Name, dtype: object

In [ ]:
# 데이터타입과 크기 확인
# df의 한 열은 Series
print(type(names))
print(names.shape)

<class 'pandas.core.series.Series'>
(891,)

In [ ]:
# 열 n개 선택
# [["열이름"]]
passenger = titanic[['Sex', "Age"]]
passenger.head()

      Sex   Age
0    male  22.0
1  female  38.0
2  female  26.0
3  female  35.0
4    male  35.0

In [ ]:
# 데이터타입과 크기 확인
print(type(passenger))
print(passenger.shape)

<class 'pandas.core.frame.DataFrame'>
(891, 2)

# 데이터 필터링
- **Boolean 인덱싱** : True값 행만 추출
- **.isin()** : 각각의 요소가 df나 series에 존재하는지 파악하여 T/F값 반환
- **Boolean 인덱싱 + .isin()** : 데이터의 특정 범위만 추출
- **.isna()** : 결측값은 T, 그 외 F 반환
- **.notna()** : 결측값은 F, 그 외 T 반환

In [ ]:
# 35세 이상인 데이터
print(passenger['Age']>=35)

0      False
1       True
2      False
3       True
4       True
       ...
886    False
887    False
888    False
889    False
890    False
Name: Age, Length: 891, dtype: bool

In [ ]:
# 35세 이상인 데이터 : Ture인 값만 추출
above35 = passenger[passenger["Age"]>=35]
above35.head()

       Sex   Age
1   female  38.0
3   female  35.0
4     male  35.0
6     male  54.0
11  female  58.0

In [ ]:
# titanic 데이터 확인
titanic.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [ ]:
# .isin() : 각각의 요소가 df나 series에 존재하는지 파악하여 T/F 반환
# Pclass 변수의 값이 1일 경우, T/F 반환
titanic["Pclass"].isin([1])

0      False
1       True
2      False
3       True
4      False
       ...
886    False
887     True
888    False
889     True
890    False
Name: Pclass, Length: 891, dtype: bool

In [ ]:
# Boolean인덱싱 + .isin() : 데이터의 특정 범위만 추출
# Pclass 값이 1인 경우만 추출하여 class1에 저장
class1 = titanic[titanic["Pclass"].isin([1])]
class1.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S
23,24,1,1,"Sloper, Mr. William Thompson",male,28.0,0,0,113788,35.5000,A6,S

In [ ]:
# passenger 데이터 확인
passenger.head()

      Sex   Age
0    male  22.0
1  female  38.0
2  female  26.0
3  female  35.0
4    male  35.0

In [ ]:
# Boolean 인덱싱 + .isin() : 데이터의 특정 부분 추출
# Age값이 20~30까지의 범위만 추출하여 Age2030으로 저장
import numpy as np
age2030 = passenger[passenger["Age"].isin(np.arange(20,31))]
age2030.head()

       Sex   Age
0     male  22.0
2   female  26.0
8   female  27.0
12    male  20.0
23    male  28.0

In [ ]:
# .isna() : 결측값은 T 반환
passenger["Age"].isna()[0:7]

0    False
1    False
2    False
3    False
4    False
5     True
6    False
Name: Age, dtype: bool

In [ ]:
# 결측값 확인
ages = passenger[passenger["Age"].isna()]
ages.head()

       Sex  Age
5     male  NaN
17    male  NaN
19  female  NaN
26    male  NaN
28  female  NaN

In [ ]:
# .natna() : 결측값은 F 반환
passenger["Age"].notna()[0:7]

0     True
1     True
2     True
3     True
4     True
5    False
6     True
Name: Age, dtype: bool

In [ ]:
# 결측값 확인
ages = passenger[passenger["Age"].notna()]
ages.head()

      Sex   Age
0    male  22.0
1  female  38.0
2  female  26.0
3  female  35.0
4    male  35.0

# 결측치 제거
- **.dropna(axis=0)** == **.dropna()**
  - 결측값이 들어있는 행 전체 삭제
- **.dropna(axis=1)**
  - 결측값이 들어있는 열 전체 삭제
- **.notna()**
  - 결측값은 F, 그 외 T 반환

In [2]:
import numpy as np
import pandas as pd

In [49]:
# csv 파일 불러오기
filename = "/content/train.csv"
titanic = pd.read_csv(filename)

In [5]:
# 데이터 확인
titanic.head(3)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S

In [8]:
# .dropna(axis=0) : 결측 행 삭제
titanic.dropna().head(3)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S

In [9]:
# .dropna(axis=1) : 결측 열 삭제
titanic.dropna(axis=1).head(3)

,PassengerId,Survived,Pclass,Name,Sex,SibSp,Parch,Ticket,Fare
0,1,0,3,"Braund, Mr. Owen Harris",male,1,0,A/5 21171,7.2500
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,1,0,PC 17599,71.2833
2,3,1,3,"Heikkinen, Miss. Laina",female,0,0,STON/O2. 3101282,7.9250

# 특정 행, 열 선택
- **.loc[  ]** : 행 이름, 열 이름으로 선택
  - DF.loc["행 이름", "열 이름"]
- **.iloc[  ]** : 행 번호, 열 번호로 선택
  - DF.iloc[행 번호, 열 번호]

In [11]:
# .loc["행 이름", "열 이름"]
# 35세 넘는 사람의 이름과 나이 출력
names35 = titanic.loc[titanic["Age"]>35, ["Name", "Age"]]
names35.head(3)

                                                 Name   Age
1   Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0
6                             McCarthy, Mr. Timothy J  54.0
11                           Bonnell, Miss. Elizabeth  58.0

In [13]:
# .iloc[행 번호, 열 번호]
# 1번째 행부터 3번째 행 까지의 0번째 열 값을 "No Name"으로 변경
names35.iloc[[1,2,3], 0] = "No Name"
names35.head()

                                                 Name   Age
1   Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0
6                                             No Name  54.0
11                                            No Name  58.0
13                                            No Name  39.0
15                   Hewlett, Mrs. (Mary D Kingcome)   55.0

# 데이터 통계
- **.mean()** : 평균
- **.median()** : 중앙값
- **.describe()** : 통계값 요약
  - 평균, 표준편차, 최소값, 4분할값, 최대값
- **.agg()** : 여러 열에 다양한 함수 적용
  - 모든 열에 같은 함수 매핑 : group.agg([함수1, 함수2, ...])
  - 각 열마다 다른 함수 매핑 : group.agg({'열1':함수1, '열2':함수2, ...})
- **.groupby()** : 그룹별 집계
- **.value_counts()** : 값의 개수

In [14]:
# .mean() : 평균
print(titanic["Age"].mean())

29.69911764705882

In [15]:
# .median() : 중앙값
print(titanic["Age"].median())

28.0

In [16]:
# .describe() : 다양한 통계량 요약
print(titanic[["Age", "Fare"]].describe())

              Age        Fare
count  714.000000  891.000000
mean    29.699118   32.204208
std     14.526497   49.693429
min      0.420000    0.000000
25%     20.125000    7.910400
50%     28.000000   14.454200
75%     38.000000   31.000000
max     80.000000  512.329200

In [27]:
# .agg([함수1, 함수2, ...]) : 모든 열에 여러 함수 매핑
# print(titanic.agg(['mean', 'median', 'std']))
# error : 숫자가 아닌 열도 존재함

# 숫자형 데이터 열에만 적용
num_cols = titanic.select_dtypes(include="number")
print(num_cols.agg(["mean", "median", "std", "max", "min"]))

        PassengerId  Survived    Pclass        Age     SibSp     Parch  \
mean     446.000000  0.383838  2.308642  29.699118  0.523008  0.381594
median   446.000000  0.000000  3.000000  28.000000  0.000000  0.000000
std      257.353842  0.486592  0.836071  14.526497  1.102743  0.806057
max      891.000000  1.000000  3.000000  80.000000  8.000000  6.000000
min        1.000000  0.000000  1.000000   0.420000  0.000000  0.000000

              Fare
mean     32.204208
median   14.454200
std      49.693429
max     512.329200
min       0.000000

In [28]:
# .agg({"열1":함수1, "열2":함수2, ...}) : 각 열마다 여러 함수 매핑
print(titanic.agg({"Age" : ["mean", "min", "max"],
                   "Fare" : ["mean", "median", "std"]}))

              Age       Fare
mean    29.699118  32.204208
min      0.420000        NaN
max     80.000000        NaN
median        NaN  14.454200
std           NaN  49.693429

In [29]:
# .groupby() : 그룹 별 집계
# 성별 별 생존율 평균
survive = titanic.groupby("Sex")["Survived"].mean()
(survive * 100).head()

Sex
female    74.203822
male      18.890815
Name: Survived, dtype: float64

In [30]:
# .value_counts() : 값 개수
titanic["Pclass"].value_counts()

Pclass
3    491
1    216
2    184
Name: count, dtype: int64

# 행, 열의 추가
- 행 추가 : **DF.loc['추가하려는 행 이름'] = 값**
- 열 추가 : **DF['추가하려는 열 이름'] = 값**

### 행 추가

In [40]:
# 데이터 확인
titanic.tail(3)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q

In [41]:
# 데이터 크기 확인
print(titanic.shape)

(891, 12)

In [42]:
# 행 추가 : DF.loc['추가하려는 행 이름'] = 값
newRow = titanic.iloc[0,:] # newRow에 0번째 행, 모든 열 삽입
titanic.loc[891] = newRow
titanic.tail(3)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q
891,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.25,NaN,S

In [43]:
# 늘어난 행 수 확인 : 891 -> 892
print(titanic.shape)

(892, 12)

### 열 추가

In [45]:
# 열 추가 : DF['추가하려는 열 이름'] = 값
titanic["3Pclass"] = titanic["Pclass"]*3
titanic.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,3Pclass
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,9
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,3
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,9
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,3
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,9

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,3Pclass
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,9
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,3
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,9
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,3
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,9

In [46]:
# 늘어난 열 수 확인 : 12 -> 13
print(titanic.shape)

(892, 13)

# 행, 열의 삭제
- 행 삭제 : **DF.drop(index, axis=0)**
- 열 삭제 : **DF.drop(변수명, axis=1)**

### 행 삭제

In [50]:
# 행 삭제 : .drop(index, axis=0)
titanic = titanic.drop(np.arange(880, 890), axis=0)
titanic # 행 수 891 -> 881

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
876,877,0,3,"Gustafsson, Mr. Alfred Ossian",male,20.0,0,0,7534,9.8458,NaN,S
877,878,0,3,"Petroff, Mr. Nedelio",male,19.0,0,0,349212,7.8958,NaN,S
878,879,0,3,"Laleff, Mr. Kristo",male,NaN,0,0,349217,7.8958,NaN,S
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,83.1583,C50,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

### 열 삭제

In [51]:
# 열 삭제 : .drop(변수명, axis=1)
titanic = titanic.drop("Pclass", axis=1)
titanic # 열 수 12 -> 11

,PassengerId,Survived,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...
876,877,0,"Gustafsson, Mr. Alfred Ossian",male,20.0,0,0,7534,9.8458,NaN,S
877,878,0,"Petroff, Mr. Nedelio",male,19.0,0,0,349212,7.8958,NaN,S
878,879,0,"Laleff, Mr. Kristo",male,NaN,0,0,349217,7.8958,NaN,S
879,880,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,83.1583,C50,C
890,891,0,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q