# 1주차 미션
## 데이터 사이언스를 위한 파이썬과 판다스 동기부여

# 문제 1
- 여러분은 파이썬을 통해 설문조사 문항의 응답내역을 분석하게 되었습니다.

- 문항별 응답내용에는 하나의 응답만 할 수 있는 single choice 문제와 여러 응답을 선택할 수 있는 multiple choice 문제가 있습니다.

- 2개를 구분하기 위해 single choice 문항 번호에 "_"를 표기하지 않기로 했습니다.

- 문항별 응답내역이 'question'에 담겨 있을 때, **조건문과 반복문을 사용하여** 아래와 같은 결과가 출력되도록 코드를 작성해보세요.

- 출력 예시

```['Q2', 'Q3', 'Q4', 'Q5', 'Q8', 'Q9']```

```
# 응답 설문 문항
question = ['Q2', 'Q3', 'Q4', 'Q5', 'Q6_1', 'Q6_2', 'Q6_3', 'Q6_4', 'Q6_5', 'Q6_6',
       'Q6_7', 'Q6_8', 'Q6_9', 'Q6_10', 'Q6_11', 'Q6_12', 'Q7_1', 'Q7_2',
       'Q7_3', 'Q7_4', 'Q7_5', 'Q7_6', 'Q7_7', 'Q8', 'Q9', 'Q10_1', 'Q10_2',
       'Q10_3']```

In [1]:
# 응답 설문 문항
question = ['Q2', 'Q3', 'Q4', 'Q5', 'Q6_1', 'Q6_2', 'Q6_3', 'Q6_4', 'Q6_5', 'Q6_6',
       'Q6_7', 'Q6_8', 'Q6_9', 'Q6_10', 'Q6_11', 'Q6_12', 'Q7_1', 'Q7_2',
       'Q7_3', 'Q7_4', 'Q7_5', 'Q7_6', 'Q7_7', 'Q8', 'Q9', 'Q10_1', 'Q10_2',
       'Q10_3']

In [3]:
# single choice 문항만 담을 리스트 생성
single_choice = []

# 복수 응답 문항이 아닌지 "_" 포함 여부로 판단하여
# 아니라면 해당 문항 번호를 single_choice 리스트에 담기
for i in question:
    if "_" not in i:
        single_choice.append(i)

# single choice 리스트 출력
print(single_choice)

['Q2', 'Q3', 'Q4', 'Q5', 'Q8', 'Q9']

# 문제 2
- 한스 로슬링(Hans Rosling, 1948년 7월 27일 ~ 2017년 2월 7일)은 스웨덴의 의사이자 통계학자로 비영리 벤처 갭마인더 재단의 공동설립자이기도 합니다. 빅데이터를 가장 잘 활용하는 보건 통계학자로 알려져 있습니다. 베스트셀러 책인 "팩트풀니스" 저자이기도 합니다.
- 갭마인더 사이트에서는 연도별, 국가별 GDP와 기대수명 데이터를 제공하고 있는데, 대표적으로 파이썬 라이브러리 중 'seaborn'에서 제공되는 예제 데이터가 있습니다. 오늘은 이 데이터를 활용해 문제를 풀어보겠습니다.
- 다음의 데이터는 연도, 국가별 기대수명을 나타내고 있는 데이터 입니다. ***2011년 부터의 연도별, 국가별 평균 기대수명***을 구해주세요. (2011년도 포함되게 구합니다.)


- [필수 조건]
    - **groupby** 나 **pivot_table**을 활용합니다.
    - groupby 로 구할 때 **unstack()**이라는 기능을 사용하여 아래와 같이 컬럼에 인덱스 값을 올려서 표기할 수 있습니다.
    - 만약 행에는 '연도'가, 열에 '국가'가 들어있고 수치 데이터의 결과값이 아래와 같다면, 출력형태는 조금 달라도 괜찮습니다.
    - 데이터는 다음의 방법으로 읽어옵니다.

    ```
    import pandas as pd
    df = pd.read_csv("https://raw.githubusercontent.com/mwaskom/seaborn-data/master/healthexp.csv")
    df
    ```

In [5]:
# 연도, 국가별 기대수명 데이터 불러오기
import pandas as pd
df = pd.read_csv("https://raw.githubusercontent.com/mwaskom/seaborn-data/master/healthexp.csv")
df

     Year        Country  Spending_USD  Life_Expectancy
0    1970        Germany       252.311             70.6
1    1970         France       192.143             72.2
2    1970  Great Britain       123.993             71.9
3    1970          Japan       150.437             72.0
4    1970            USA       326.961             70.9
..    ...            ...           ...              ...
269  2020        Germany      6938.983             81.1
270  2020         France      5468.418             82.3
271  2020  Great Britain      5018.700             80.4
272  2020          Japan      4665.641             84.7
273  2020            USA     11859.179             77.0

[274 rows x 4 columns]

## groupby

In [15]:
# 연도별 국가별 평균 기대수명을 life_expectancy 로 저장
life_expectancy = df.groupby(['Year', "Country"])['Life_Expectancy'].mean().unstack()
life_expectancy

Country  Canada  France  Germany  Great Britain  Japan   USA
Year
1970        NaN    72.2     70.6           71.9   72.0  70.9
1971       72.8     NaN     70.8           71.9   72.9  71.2
1972        NaN     NaN     71.0            NaN   73.2  71.2
1973        NaN     NaN     71.3            NaN   73.4  71.4
1974        NaN     NaN     71.5            NaN   73.7  72.0
1975        NaN    73.0     71.4            NaN   74.3  72.7
1976       73.8     NaN     71.8            NaN   74.8  72.9
1977        NaN     NaN     72.5            NaN   75.3  73.3
1978        NaN     NaN     72.4            NaN   75.7  73.5
1979       75.1     NaN     72.8            NaN   76.2  73.9
1980       75.2    74.3     72.9           73.2   76.1  73.7
1981       75.5     NaN     73.2           73.8   76.5  74.1
1982       75.6     NaN     73.5           74.1   76.9  74.5
1983       75.9     NaN     73.8           74.3   77.0  74.6
1984       76.2     NaN     74.3           74.5   77.4  74.7
1985       76.3    75.4     75.0           74.7   77.6  74.7
1986       76.5     NaN     75.2           74.8   78.1  74.7
1987       76.7     NaN     75.6           75.2   78.5  74.9
1988       76.8     NaN     75.9           75.3   78.4  74.9
1989       77.1     NaN     76.0           75.4   78.8  75.1
1990       77.3    77.0     77.3           75.7   78.9  75.3
1991       77.6    77.2      NaN           75.9   79.1  75.5
1992       77.8    77.5     76.1           76.3   79.2  75.7
1993       77.8    77.5     76.1           76.2   79.4  75.5
1994       77.9    78.0     76.5           76.8   79.8  75.7
1995       78.0    78.1     76.6           76.7   79.6  75.7
1996       78.2    78.2     76.9           76.9   80.3  76.1
1997       78.3    78.6     77.3           77.2   80.5  76.5
1998       78.6    78.8     77.7           77.3   80.6  76.7
1999       78.8    78.9     77.9           77.5   80.5  76.7
2000       79.1    79.2     78.2           77.9   81.2  76.7
2001       79.3    79.3     78.5           78.2   81.5  76.9
2002       79.5    79.4     78.5           78.3   81.8  77.0
2003       79.6    79.3     78.6           78.4   81.8  77.1
2004       79.9    80.3     79.2           79.0   82.1  77.6
2005       80.0    80.4     79.4           79.2   82.0  77.6
2006       80.4    81.0     79.8           79.5   82.4  77.8
2007       80.5    81.2     80.1           79.7   82.6  78.1
2008       80.7    81.4     80.2           79.8   82.7  78.1
2009       80.9    81.5     80.3           80.4   83.0  78.5
2010       81.2    81.8     80.5           80.6   82.9  78.6
2011       81.4    82.3     80.5           81.0   82.7  78.7
2012       81.6    82.1     80.6           81.0   83.2  78.8
2013       81.7    82.3     80.6           81.1   83.4  78.8
2014       81.8    82.8     81.2           81.4   83.7  78.9
2015       81.9    82.4     80.7           81.0   83.9  78.7
2016       82.0    82.7     81.0           81.2   84.1  78.7
2017       81.9    82.7     81.1           81.3   84.2  78.6
2018       82.0    82.8     81.0           81.3   84.3  78.7
2019       82.2    82.9     81.3           81.4   84.4  78.8
2020       81.7    82.3     81.1           80.4   84.7  77.0

In [35]:
# 연도별 국가별 평균 기대수명 life_expectancy 을
# 2011년부터의 데이터만 저장
life_expectancy_2011 = life_expectancy[life_expectancy.index >= 2011]
life_expectancy_2011

Country  Canada  France  Germany  Great Britain  Japan   USA
Year
2011       81.4    82.3     80.5           81.0   82.7  78.7
2012       81.6    82.1     80.6           81.0   83.2  78.8
2013       81.7    82.3     80.6           81.1   83.4  78.8
2014       81.8    82.8     81.2           81.4   83.7  78.9
2015       81.9    82.4     80.7           81.0   83.9  78.7
2016       82.0    82.7     81.0           81.2   84.1  78.7
2017       81.9    82.7     81.1           81.3   84.2  78.6
2018       82.0    82.8     81.0           81.3   84.3  78.7
2019       82.2    82.9     81.3           81.4   84.4  78.8
2020       81.7    82.3     81.1           80.4   84.7  77.0

## pivot_table

In [45]:
# 전체 기간의 연도별 국가별 평균 기대수명을 life_expectancy2 에 저장
life_expectancy2 = df.pivot_table(index="Year", columns='Country', values = 'Life_Expectancy')
life_expectancy2

Country  Canada  France  Germany  Great Britain  Japan   USA
Year
1970        NaN    72.2     70.6           71.9   72.0  70.9
1971       72.8     NaN     70.8           71.9   72.9  71.2
1972        NaN     NaN     71.0            NaN   73.2  71.2
1973        NaN     NaN     71.3            NaN   73.4  71.4
1974        NaN     NaN     71.5            NaN   73.7  72.0
1975        NaN    73.0     71.4            NaN   74.3  72.7
1976       73.8     NaN     71.8            NaN   74.8  72.9
1977        NaN     NaN     72.5            NaN   75.3  73.3
1978        NaN     NaN     72.4            NaN   75.7  73.5
1979       75.1     NaN     72.8            NaN   76.2  73.9
1980       75.2    74.3     72.9           73.2   76.1  73.7
1981       75.5     NaN     73.2           73.8   76.5  74.1
1982       75.6     NaN     73.5           74.1   76.9  74.5
1983       75.9     NaN     73.8           74.3   77.0  74.6
1984       76.2     NaN     74.3           74.5   77.4  74.7
1985       76.3    75.4     75.0           74.7   77.6  74.7
1986       76.5     NaN     75.2           74.8   78.1  74.7
1987       76.7     NaN     75.6           75.2   78.5  74.9
1988       76.8     NaN     75.9           75.3   78.4  74.9
1989       77.1     NaN     76.0           75.4   78.8  75.1
1990       77.3    77.0     77.3           75.7   78.9  75.3
1991       77.6    77.2      NaN           75.9   79.1  75.5
1992       77.8    77.5     76.1           76.3   79.2  75.7
1993       77.8    77.5     76.1           76.2   79.4  75.5
1994       77.9    78.0     76.5           76.8   79.8  75.7
1995       78.0    78.1     76.6           76.7   79.6  75.7
1996       78.2    78.2     76.9           76.9   80.3  76.1
1997       78.3    78.6     77.3           77.2   80.5  76.5
1998       78.6    78.8     77.7           77.3   80.6  76.7
1999       78.8    78.9     77.9           77.5   80.5  76.7
2000       79.1    79.2     78.2           77.9   81.2  76.7
2001       79.3    79.3     78.5           78.2   81.5  76.9
2002       79.5    79.4     78.5           78.3   81.8  77.0
2003       79.6    79.3     78.6           78.4   81.8  77.1
2004       79.9    80.3     79.2           79.0   82.1  77.6
2005       80.0    80.4     79.4           79.2   82.0  77.6
2006       80.4    81.0     79.8           79.5   82.4  77.8
2007       80.5    81.2     80.1           79.7   82.6  78.1
2008       80.7    81.4     80.2           79.8   82.7  78.1
2009       80.9    81.5     80.3           80.4   83.0  78.5
2010       81.2    81.8     80.5           80.6   82.9  78.6
2011       81.4    82.3     80.5           81.0   82.7  78.7
2012       81.6    82.1     80.6           81.0   83.2  78.8
2013       81.7    82.3     80.6           81.1   83.4  78.8
2014       81.8    82.8     81.2           81.4   83.7  78.9
2015       81.9    82.4     80.7           81.0   83.9  78.7
2016       82.0    82.7     81.0           81.2   84.1  78.7
2017       81.9    82.7     81.1           81.3   84.2  78.6
2018       82.0    82.8     81.0           81.3   84.3  78.7
2019       82.2    82.9     81.3           81.4   84.4  78.8
2020       81.7    82.3     81.1           80.4   84.7  77.0

In [48]:
# life_expectancy2 중 2011 이후의 데이터만 출력
life_expectancy2_2011 = life_expectancy2.loc[2011:]
life_expectancy2_2011

Country  Canada  France  Germany  Great Britain  Japan   USA
Year
2011       81.4    82.3     80.5           81.0   82.7  78.7
2012       81.6    82.1     80.6           81.0   83.2  78.8
2013       81.7    82.3     80.6           81.1   83.4  78.8
2014       81.8    82.8     81.2           81.4   83.7  78.9
2015       81.9    82.4     80.7           81.0   83.9  78.7
2016       82.0    82.7     81.0           81.2   84.1  78.7
2017       81.9    82.7     81.1           81.3   84.2  78.6
2018       82.0    82.8     81.0           81.3   84.3  78.7
2019       82.2    82.9     81.3           81.4   84.4  78.8
2020       81.7    82.3     81.1           80.4   84.7  77.0

# 문제 3

- 앞으로 우리는 공공데이터포털에서 데이터를 다운로드 받아 과정을 진행할 예정입니다. 본격적인 학습 이전에! 데이터를 다루는 방법이 익숙해지도록 한번 더 연습해보고, 어떤 문제를 풀 수 있을지도 함께 고민해보아요!

- 공공데이터포털에서 원하는 데이터를 다운로드 받아 경로를 설정하고, 판다스를 통해 불러와 보세요!

- 이 때, 인코딩 오류가 발생한다면 **encoding="cp949"** 옵션을 사용해 주세요!
cp949는 한글 윈도우에서 사용하는 인코딩 방식이랍니다.

In [ ]:
import pandas as pd

In [ ]:
# 대한민국 기후 평년값 파일 불러오기
filename = "/content/STCS_우리나라기후평년값_DD_20240802201055.csv"
korea_weather = pd.read_csv(filename, encoding="cp949")
korea_weather

,지점명,지점번호,일시,평균기온(°C),최고기온(°C),최저기온(°C),강수량(mm),습도(%),일조시간(hr),전운량(1/10),소형증발량(mm),현지기압(hPa),해면기압(hPa),평균풍속(m/sec)
0,속초,90,07월 03일,22.4,25.8,19.4,10.4,82.3,5.4,NaN,NaN,1002.9,1005.0,2.0
1,철원,95,07월 03일,22.9,27.4,19.1,10.8,79.9,5.0,NaN,NaN,987.3,1004.9,1.8
2,동두천,98,07월 03일,23.4,28.4,19.7,11.8,78.4,4.5,NaN,NaN,992.2,1004.9,1.4
3,파주,99,07월 03일,23.1,28.0,19.6,12.5,83.2,4.8,NaN,NaN,1001.0,1004.4,1.4
4,대관령,100,07월 03일,18.6,22.8,15.4,11.8,85.4,5.2,NaN,NaN,915.9,1005.4,3.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6784,부산진,938,08월 02일,27.9,31.8,25.0,6.8,NaN,NaN,NaN,NaN,NaN,NaN,2.1
6785,동래,940,08월 02일,27.9,32.1,24.8,6.2,NaN,NaN,NaN,NaN,NaN,NaN,1.9
6786,북구,941,08월 02일,27.4,31.6,24.3,7.5,NaN,NaN,NaN,NaN,NaN,NaN,2.3
6787,부산남구,942,08월 02일,27.7,31.1,25.1,5.2,NaN,NaN,NaN,NaN,NaN,NaN,2.1
6788,정자,949,08월 02일,26.4,30.7,22.5,4.5,NaN,NaN,NaN,NaN,NaN,NaN,2.4

In [ ]:
# 컬럼명 확인
korea_weather.columns

Index(['지점명', '지점번호', '일시', '평균기온(°C)', '최고기온(°C)', '최저기온(°C)', '강수량(mm)',
       '습도(%)', '일조시간(hr)', '전운량(1/10)', '소형증발량(mm)', '현지기압(hPa)', '해면기압(hPa)',
       '평균풍속(m/sec)'],
      dtype='object')

## 대한민국 기후 평년값 데이터로 할 수 있는 분석
- 시도별 평균 기온, 강수량 등 분석
- 강수량과 습도 간 상관관계 분석
- 겨울철 가장 추운 지역과 여름철 가장 더운 지역 구하기
    - 지역별 전기세 등의 데이터와 함께 분석하면, 기온과 전기세의 상관관계 등도 구할 수 있을 것 같습니다
- 겨울철 가장 따뜻한 지역과 여름철 가장 시원한 지역 구하기
    - 지역별 관광객 수 등의 데이터와 함께 분석하여, 기온과 인기 피서지의 상관관계 등도 구해보면 재밌을 것 같습니다
- 평균풍속과 일조량이 발전량에 미치는 영향 분석하기
  - 지역별 풍속, 태양광 발전량 데이터를 종속변수로 두고, 평균풍속과 일조량을 독립변수로 설정해 회귀분석해도 좋을 것 같습니다
- 내삽 기법을 활용해 관측지점 외 지역 기온 구하기
 - 크리깅 등 다양한 내삽 기법을 이용해서 미지점의 기온 등을 구할 수 있을 것 같습니다.